### ISSUE TITLE
Benchmark secure servers using LDAPS

### ISSUE THREAD

**Issue by ferfebles** [hamano/lb#3]
Tried to launch a search benchmark using LDAPS but it says: 

Can't contact LDAP server.

The same server can be contacted using LDAP.

By the way, thanks for your work with lb. It has been very useful to test the performance of the servers we are deploying.

**Comment by msquirejc** [comment]
NAME:
   lb bind - LDAP BIND Benchmarking

USAGE:
   lb bind [command options] [arguments...]

OPTIONS:
   --verbose value, -v value  How much troubleshooting info to print (default: 0)
   --quiet, -q                Quiet flag
   -n value                   Number of requests to perform (default: 1)
   -c value                   Number of multiple requests to make (default: 1)
   -D value                   Bind DN (default: "cn=Manager,dc=example,dc=com")
   -w value                   Bind Secret (default: "secret")
   -b value                   BaseDN (default: "dc=example,dc=com")
   --starttls, -Z             Use StartTLS
   --short                    short result
   --first value              first id (default: 1)
   --last value               last id (default: 0)

You can use the -Z option or possibly hit the 636 port to start the TLS handshake. I am new to the project and need this support too. Hope that helps.
