### ISSUE TITLE
Could you push a git tag?

### ISSUE THREAD

**Issue by kazuhisya** [hamano/lb#8]
I want you to push a `git tag`. and there are two advantages to this.

- We can easily check this software version.
- We can easily get the archive. ([It is a feature of github](https://help.github.com/en/articles/about-releases))

**Comment by hamano** [comment]
I just tagged 0.9.3 and 0.9.4. I'll push tag from now.
Thanks.

**Comment by kazuhisya** [comment]
🎉  Thank you so much for your prompt work.
